# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d530f003821dc74f39ab6eaa0b71f05c56401b47a78e4fb8930bb0fa3e3c57c6025902502720a5fe93ab131b2ce84ab7b0a3febb90b86d613f4a6bc4b373926

test:
  secret_key_base: 0f3441479df7a242baa5a6b78303ddbf02968c73d0579ebe2acea18fde542b826af31fc25007b6928799e327dbfcc1a48f086a8c6967328c853119b890114992

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
